### ISSUE TITLE
Long passwords screw up display

### ISSUE THREAD

**Issue by tobbbles** [spaceshuttl/coffer#12]
## How to reproduce

Add a really, really long text entry
## Possible fix

Add line breaks to long passwords, or enforce max-width on table field

**Comment by awnumar** [comment]
How would a max-width work? Limiting password sizes to a certain length or just letting them trail off the screen while keeping the width of the input fixed?

Personally I think adding line-breaks is not optimal.

**Comment by tobbbles** [comment]
It'd probably be best to have a horizontally scrolling field which can be
navigated via the cursor.

Should be just some simple CSS, I hope.

**Comment by tobbbles** [comment]
Will be fixed with 

```
overflow-x: scroll;
max-width: Xem;
```

**Comment by tobbbles** [comment]
Style aside, this is what the fix looks like:

http://i.imgur.com/xWVDCUU.jpg

**Comment by tobbbles** [comment]
fixed by d6dcf7a8b85914d5f141a2074d38a88587f30192
